# Generated by Django 3.0.6 on 2020-06-04 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplereservation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='simplereservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='simplereservation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='simplereservation',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='simplereservation',
            name='user',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='simplereservation',
            name='reservation_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.Reservation'),
            preserve_default=False,
        ),
    ]
